import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastContainer } from "react-toastify";
import ConditionalNav from "../components/ConditionalNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon-32x32.png",
    apple: "/images/favicon-32x32.png",
    shortcut: "/images/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-red-100 antialiased h-[90vh]`}
      >
      <div className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-r from-emerald-400 to-teal-200 h--full min-h-screen`}>
        <ToastContainer />
        <ConditionalNav>
          <Navbar />
        </ConditionalNav>
        {children}
      </div>

      </body>
    </html>
  );
}
