# Generated by Django 5.2.7 on 2025-10-26 21:47

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("secret", models.TextField(max_length=100)),
                (
                    "number_attempts",
                    models.SmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(3)],
                    ),
                ),
            ],
        ),
    ]
