# Generated by Django 5.2.7 on 2025-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="client_id",
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
