# Generated by Django 5.2.7 on 2025-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
