# Generated by Django 5.2.7 on 2025-10-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
