# Generated by Django 5.2.7 on 2025-10-26 21:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_client_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
