# Generated by Django 5.2.7 on 2025-11-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_status_clientcreationaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcreationaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("CLIENT_CREATED", "Client Created"),
                    ("CLIENT_ACTIVATED", "Client Activated"),
                    ("CLIENT_REJECTED", "Client Rejected"),
                    ("FAILED_VALIDATION", "Failed Validation"),
                ],
                max_length=100,
            ),
        ),
    ]
