{
 "title": "Latency",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|django.views.static.serve|passcode\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|django.views.static.serve|passcode\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|django.views.static.serve|passcode\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"django.views.static.serve|prometheus-django-metrics|<unnamed view>\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"django.views.static.serve|prometheus-django-metrics|<unnamed view>\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"django.views.static.serve|prometheus-django-metrics\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50 per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, view) (rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"django.views.static.serve|prometheus-django-metrics\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}