{
 "title": "Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(django_http_requests_total_by_method_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(view) (increase(django_http_requests_total_by_view_transport_method_total{view!~\"prometheus-django-metrics|django.views.static.serve\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per method in the last hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (increase(django_http_requests_total_by_method_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily requests",
   "type": "timeseries",
   "description": "Number of HTTP requests per day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(django_http_requests_total_by_method_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}