# Generated by Django 5.2.6 on 2025-09-21 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.TextField(max_length=100)),
                (
                    "number_attempts",
                    models.SmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="broker.user"
                    ),
                ),
            ],
        ),
    ]
