# Generated by Django 5.2.6 on 2025-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0002_useropt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
