# Generated by Django 5.2.6 on 2025-09-22 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0004_alter_wallet_user_alter_useropt_user_client_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserOPT",
            new_name="ClientOTP",
        ),
    ]
