# Generated by Django 5.2.6 on 2025-09-24 00:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0007_alter_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="message",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="idempotency_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
