# Generated by Django 5.2.6 on 2025-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0008_transaction_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("D", "Deposit"), ("S", "Sale"), ("B", "Buy")],
                default="D",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
