# Generated by Django 5.2.6 on 2025-10-12 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0010_stock_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="quantity",
            new_name="initial_quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="remaining_quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Completed"),
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
