# Generated by Django 5.2.6 on 2025-10-12 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0011_rename_quantity_order_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default="a", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="broker.client",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Shares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="broker.client",
                    ),
                ),
            ],
        ),
    ]
