# Generated by Django 5.2.6 on 2025-10-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0012_remove_wallet_user_client_email_client_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="broker.client",
            ),
        ),
    ]
