# Generated by Django 5.2.6 on 2025-10-13 15:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0013_remove_wallet_user_alter_wallet_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="duration",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
