# Generated by Django 5.2.6 on 2025-10-23 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0014_order_order_id_alter_order_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                default="aaa",
                on_delete=django.db.models.deletion.CASCADE,
                to="broker.client",
            ),
            preserve_default=False,
        ),
    ]
