# Generated by Django 5.2.7 on 2025-10-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="client_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
