# Generated by Django 5.2.7 on 2025-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_walletaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE_WITHDRAWAL", "Withdraw Funds"),
                    ("UPDATE_WITHDRAWAL_STATUS", "Update Withdrawal Status"),
                ],
                max_length=50,
            ),
        ),
    ]
