# Generated by Django 5.2.7 on 2025-11-16 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_walletaudit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaudit',
            name='action',
            field=models.CharField(choices=[('CREATE_WITHDRAWAL', 'Withdraw Funds'), ('UPDATE_WITHDRAWAL_STATUS', 'Update Withdrawal Status'), ('RESERVE_FUNDS', 'Reserve Funds'), ('RELEASE_FUNDS', 'Release Funds')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReservedFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(db_index=True, editable=False)),
                ('order_id', models.UUIDField(editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('client_id'), models.F('order_id'), name='unique_reservation_per_order')],
            },
        ),
        migrations.AddField(
            model_name='walletaudit',
            name='reserved_funds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.reservedfunds'),
        ),
    ]
