services:
  broker_app:
    container_name: broker_app
    build: .
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: brokerX_db
      DJANGO_SETTINGS_MODULE: brokerX.settings
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["python", "entrypoint.py"]

  mysql:
    image: mysql:8
    container_name: broker_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brokerX_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

#TODO: add network