services:
  broker_app:
    container_name: broker_app
    build: .
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: brokerX_db
      DJANGO_SETTINGS_MODULE: brokerX.settings
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
    entrypoint: ["python", "entrypoint.py"]
    networks:
      - brokerX-network

  mysql:
    image: mysql:8
    container_name: broker_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brokerX_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - brokerX-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.1
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - brokerX-network


volumes:
  mysql_data:

networks:
  brokerX-network:
    external: true