from jwt import PyJWKClient

jwks_url = "http://keycloak:7080/realms/BrokerX/protocol/openid-connect/certs"
jwks_client = PyJWKClient(jwks_url)

token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHVWhxeG5NNktFNkwtRk9TZzE3WDZPNjVwTVVHVXhOVGVxTVBQQ0s4UXRzIn0.eyJleHAiOjE3NjA5MjczNTcsImlhdCI6MTc2MDkyNzA1NywiYXV0aF90aW1lIjoxNzYwOTI2NDMxLCJqdGkiOiJvbnJ0YWM6Y2M5YmYyZjctNWFkZC01YTVlLTM1MTEtOTEzZGM3ZDZjYmJlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo3MDgwL3JlYWxtcy9Ccm9rZXJYIiwic3ViIjoiMWE5YmFiNDEtMmM0Ny00YmQ1LTgwMzEtNjVhZDZjOTg2YTEwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicmVhY3QtYnJva2VyWCIsInNpZCI6ImNkOWE5N2Y0LTIyZjMtNzAyNy0wZWMzLTBhZDc0NzUxNTIyMiIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDozMDAwIl0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IldpbGxpYW0gTGF2b2llIiwicHJlZmVycmVkX3VzZXJuYW1lIjoid2lsbGlhbTU2OSIsImdpdmVuX25hbWUiOiJXaWxsaWFtIiwiZmFtaWx5X25hbWUiOiJMYXZvaWUiLCJlbWFpbCI6IndpbGxpYW01NjlAaG90bWFpbC5jYSJ9.J8eVtJfk2uJoqWtzmXbxuO61I93EqkHSgavsKDlWsxiTkAGUlgpm-DkrAbxCkn2WD4R2kX0p-CP2baiLsRuRa9lXXxMmlYZUTV3xGGbHjg4CZvQegAK2t9k8W1NY5i-rLSxeTS-QqrFtPu_pqBSfow4fZs9mJdmX5uguKCNVIJoMUlQGJEsXqbAQXzP0buLYzcGpFoQtyq0YBOIB-BK1ZdVkXV1A8z9w_vYRW0Jy4EQ3CO0JeJYQ_SH4CYQ4a1_NhG0w3TTtawZZ0a55ZwWV7yv29U_2or3YEV39AiEz7cJZ8JXNJbqu61HiDY69ScxDHl2B0IncoaVjFbjV9MRtSQ"

try:
    signing_key = jwks_client.get_signing_key_from_jwt(token)
    print("Signing key:", signing_key.key)
except Exception as e:
    print("Error fetching signing key:", e)
