
@startuml
start
:See the main page of the application;

if (User has an account?) then (yes)
else (no)
  :Create an account;
  :Receive verification email;
  :Click verification link;
endif

:Login;

repeat
  :Show main page;
  :User selects "Add funds";
  :Choose amount;
  :Confirm deposit;

repeat while (User stays logged in?)
:Logout;


@enduml
