# Generated by Django 5.2.7 on 2025-11-15 00:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("client_id", models.UUIDField(db_index=True)),
                (
                    "stock_symbol",
                    models.CharField(db_index=True, editable=False, max_length=100),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "order_style",
                    models.CharField(
                        choices=[("MARKET", "Market"), ("LIMIT", "Limit")],
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_executed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXECUTED", "Executed"),
                            ("PARTIALLY_EXECUTED", "Partially Executed"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_EXECUTED", "Order Executed"),
                            ("ORDER_PARTIALLY_EXECUTED", "Order Partially Executed"),
                            ("ORDER_REJECTED", "Order Rejected"),
                            ("ORDER_FAILED", "Order Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="order.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("buyer_client_id", models.UUIDField()),
                ("seller_client_id", models.UUIDField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
