# Generated by Django 5.2.7 on 2025-11-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_duration",
            field=models.CharField(
                choices=[
                    ("GTC", "Good Till Cancelled"),
                    ("IOC", "Immediate Or Cancel"),
                    ("DAY", "Day"),
                    ("GTD", "Good Till Date"),
                    ("FOK", "Fill Or Kill"),
                ],
                default="GTC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
