# Generated by Django 5.2.7 on 2025-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_order_duration_order_order_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderexecution",
            name="order",
        ),
        migrations.AddField(
            model_name="orderexecution",
            name="orders",
            field=models.ManyToManyField(related_name="executions", to="order.order"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("EXECUTED", "Executed"),
                    ("PARTIALLY_EXECUTED", "Partially Executed"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("ORDER_REJECTED", "Order Rejected"),
                    ("ORDER_FAILED", "Order Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
