# Generated by Django 5.2.7 on 2025-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_orderexecution_order_orderexecution_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("ORDER_REJECTED", "Order Rejected"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("ORDER_FAILED", "Order Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
