@startuml
    class OrderView{
        + post(request)
        + get(request)
        + put(request)
        + delete(request)
    }

    class PlaceOrderUseCase{
        + order_repository : OrderRepository
        + portfolio_repository: PortfolioRepository
        + stock_repository: StockRepository
        + wallet_repository: WalletRepository
        + execute(client_id: UUID, symbol: str, order_type: str, order_style: str, order_duration: str, quantity: int, idempotency_key: UUID, price: Decimal, end_date: datetime) : UseCaseResult
    }

    class OrderMatchingUseCase{
        + order_repository : OrderRepository
        + portfolio_repository: PortfolioRepository
        + stock_repository: StockRepository
        + wallet_repository: WalletRepository
        + execute(client_id: UUID, symbol: str, order_type: str, order_style: str, order_duration: str, quantity: int, idempotency_key: UUID, price: Decimal, end_date: datetime) : UseCaseResult
    }


    class Order{
        + client_id: UUID
        + symbol: str
        + order_type: str
        + order_style: str
        + order_duration: str
        + quantity: int
        + order_id: UUID
        + quantity_executed: int
        + price: Decimal
        + end_date: datetime
        + status: str
        + created_at: datetime
        + updated_at: datetime
        + executed_at: datime

        + validate_data()
        + to_dict(): dict
        + update_from_dto(order_dto: OrderDTO)
    }

    class OrderDTO{
        + client_id: UUID
        + symbol: str
        + order_type: str
        + order_style: str
        + order_duration: str
        + quantity: int
        + order_id: UUID
        + quantity_executed: int
        + price: Decimal
        + end_date: datetime
        + status: str
        + created_at: datetime
        + updated_at: datetime
        + executed_at: datime

        + to_dict(): dict
        + get_order_from_dto(): Order
    }

    class OrderInvalidException{
        + user_message: str
        + log_message: str
        + error_code: int
    }

 note right of OrderInvalidException
    Extends the basic Exception class
 end note

    class WalletRepository <<abstract>> {
        + reserve_funds(order: Order)
        + release_funds(order_id: UUID, client_id: UUID)
    }

    class WalletService  {
        + reserve_funds(order: Order)
        + release_funds(order_id: UUID, client_id: UUID)
    }

    class StockRepository <<abstract>> {
        + update_top_of_book(order: Order)
    }

    class StockService {
        + update_top_of_book(order: Order)
    }

    class PortfolioRepository <<abstract>> {
        + reserve_holdings(order: Order)
        + release_holdings(order: Order)
    }

    class PortfolioService {
        + reserve_holdings(order: Order)
        + release_holdings(order: Order)
    }

    class OrderRepository<<abstract>> {
        + add_order(order: Order, idempotency_key: UUID)
        + get_potential_matches(order: Order): [Order]
        + get_orders_by_client(client_id: UUID): [Order]
        + delete_order(client_id: UUID, order_id: UUID): Order
        + delete_order_rollback(client_id: UUID, order_id: UUID, previous_status: str)
        + execute_order(order: Order, matching_orders: [Order]): dict
    }

    class DjangoOrderRepository {
        + add_order(order: Order, idempotency_key: UUID)
        + get_potential_matches(order: Order): [Order]
        + get_orders_by_client(client_id: UUID): [Order]
        + delete_order(client_id: UUID, order_id: UUID): Order
        + delete_order_rollback(client_id: UUID, order_id: UUID, previous_status: str)
        + execute_order(order: Order, matching_orders: [Order]): dict
    }

    class OrderDAO <<abstract>> {
        + client_id: UUID,
        +symbol: str,
        + order_type: str,
        + order_style: str,
        + order_duration: str,
        + quantity: int,
        + idempotency_key: UUID,
        + end_date: datetime,
        + price: Decimal

        + add_order(order: Order, idempotency_key: UUID)
        + get_potential_matches(order: Order): [Order]
        + get_orders_by_client(client_id: UUID): [Order]
        + delete_order(client_id: UUID, order_id: UUID): Order
        + delete_order_rollback(client_id: UUID, order_id: UUID, previous_status: str)
        + execute_order(order: Order, matching_orders: [Order]): dict
    }

class MySQLOrderDAO  {
        + client_id: UUID,
        +symbol: str,
        + order_type: str,
        + order_style: str,
        + order_duration: str,
        + quantity: int,
        + idempotency_key: UUID,
        + end_date: datetime,
        + price: Decimal

        + add_order(order: Order, idempotency_key: UUID)
        + get_potential_matches(order: Order): [Order]
        + get_orders_by_client(client_id: UUID): [Order]
        + delete_order(client_id: UUID, order_id: UUID): Order
        + delete_order_rollback(client_id: UUID, order_id: UUID, previous_status: str)
        + execute_order(order: Order, matching_orders: [Order]): dict
    }

class RedisOrder {
    + set_orders_by_client(client_id: UUID, orders: [Order])
    + get_orders_by_client(client_id: UUID): [Order]
    + redis_get_orders_by_stock(symbol: str): [Order]
    + set_order(client_id: UUID, order: Order)
    + delete_order(order_id: UUID, client_id: UUID)
}

class OrderCreatedHandler {
    + get_event_type(): str
    + handle(event_data: dict)
}

class OrderEventProducer {
    + get_instance(): KafkaProducer
}

OrderView --> PlaceOrderUseCase
PlaceOrderUseCase --> OrderRepository
OrderMatchingUseCase --> OrderRepository
PlaceOrderUseCase --> WalletRepository
PlaceOrderUseCase --> StockRepository
PlaceOrderUseCase --> PortfolioRepository
OrderRepository--> OrderDAO
PlaceOrderUseCase --> Order
OrderMatchingUseCase --> Order
OrderRepository--> Order
PlaceOrderUseCase --> OrderInvalidException
Order --> OrderInvalidException
Order --> OrderDTO
OrderRepository--> OrderDTO
DjangoOrderRepository --> RedisOrder
OrderCreatedHandler --> OrderMatchingUseCase
OrderCreatedHandler --> OrderEventProducer

StockService --|> StockRepository
WalletRepository --|> WalletService
PortfolioRepository--|> PortfolioService
OrderRepository--|> DjangoOrderRepository
OrderDAO --|> MySQLOrderDAO

@enduml