# Generated by Django 5.2.7 on 2025-11-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_holdings_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdings",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="portfolio.portfolio",
            ),
        ),
    ]
