# Generated by Django 5.2.7 on 2025-11-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_holdings_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="client_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="holdings",
            constraint=models.UniqueConstraint(
                models.F("client_id"),
                models.F("symbol"),
                name="unique_symbol_per_client",
            ),
        ),
    ]
