# Generated by Django 5.2.7 on 2025-11-22 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_portfolio_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdings",
            name="reserved_for_sale",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
