# Generated by Django 5.2.7 on 2025-11-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_holdings_reserved_for_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdings",
            name="name",
            field=models.CharField(default="", editable=False, max_length=100),
        ),
    ]
