# Generated by Django 5.2.7 on 2025-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_holdings_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdings",
            name="name",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100, null=True
            ),
        ),
    ]
