services:
  stock-app:
    build: .
    volumes:
      - .:/app
    environment:
      DB_HOST: stock-mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: stock_db
    ports:
      - "8004:8004"
    expose:
      - "8004"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["python", "entrypoint.py"]
    networks:
      - brokerx-network

  mysql:
    image: mysql:8
    container_name: stock-mysql
    restart: unless-stopped
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - stock_mysql_data:/var/lib/mysql
      - ./mysql-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - brokerx-network

  redis:
    container_name: stock-redis
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - brokerx-network

volumes:
  stock_mysql_data:

networks:
  brokerx-network:
    external: true