{
 "title": "Errors",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(django_http_responses_total_by_status_view_method_total{status=~\"4..|5..\", status!=\"401\"}[5m])) * 100) / (sum(rate(django_http_responses_total_by_status_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(django_http_responses_total_by_status_view_method_total{status=~\"5..\"}[5m])) * 100) / (sum(rate(django_http_responses_total_by_status_total[5m]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error by status code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(django_http_responses_total_by_status_view_method_total{status!~\"2..|3..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}