@startuml Component diagram

package "Domain (Core)" {
    [User]
    [UserService]
}

package "Ports (Interfaces)" {
    interface UserRepository
}

package "Adapters" {
    [UserRepositoryDAO]
    [UserController]
    [WebView]
}

[UserController] --> [UserService] : uses domain services
[UserService] --> UserRepository : persistence interface
[UserRepositoryDAO] ..|> UserRepository

[WebView] --> [UserController] : user interaction

[UserService] --> [User] : business logic
UserRepository --> [User] : manages persistence

@enduml
