name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    env:
      REPO_DIR: BrokerX

    steps:
      - name: Clone repository
        shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd ~
          if [ ! -d "$REPO_DIR" ]; then
            git clone https://github.com/$GITHUB_REPOSITORY.git "$REPO_DIR"
          else
            cd "$REPO_DIR"
            git fetch origin
            git reset --hard origin/main
          fi

      - name: Make deploy script executable
        run: chmod +x "$HOME/$REPO_DIR/brokerX/deploy.sh"

      - name: Deploy application
        run: "$HOME/$REPO_DIR/brokerX/deploy.sh"
