name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    env:
        REPO_NAME: ${{ github.repository_name }}

    steps:
      - name: Clone repository
        shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd ~
          if [ ! -d "$REPO_NAME" ]; then
            git clone https://github.com/${GITHUB_REPOSITORY}.git "${{ env.REPO_NAME }}"
          fi

      - name: Give permission
        working-directory: ~/${{ env.REPO_NAME }}
        run: chmod +x brokerX/deploy.sh

      - name: Deploy
        working-directory: ~/${{ env.REPO_NAME }}
        run: ./deploy.sh