name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        working-directory: brokerX
        run: ./deploy.sh