from django.core.management.base import BaseCommand
from stock.models import Stock


class Command(BaseCommand):
    help = "Seed the stock service with mock data."

    def handle(self, *args, **options):
        self.stdout.write("Seeding stock data...")

        Stock.objects.get_or_create(
            symbol="AAPL",
            name="Apple Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=5.00,
            tick_size=0.01,
            last_price=150.00,
            open_price=148.00,
            high_price=151.00,
            low_price=147.00,
            close_price=149.00,
            bid_price=149.50,
            bid_size=100,
            ask_price=150.50,
            ask_size=100,
            volume=1000000,
        )
        Stock.objects.get_or_create(
            symbol="GOOGL",
            name="Alphabet Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=10.00,
            tick_size=0.01,
            last_price=2800.00,
            open_price=2780.00,
            high_price=2820.00,
            low_price=2770.00,
            close_price=2790.00,
            bid_price=2795.00,
            bid_size=50,
            ask_price=2805.00,
            ask_size=50,
            volume=500000,
        )
        Stock.objects.get_or_create(
            symbol="MSFT",
            name="Microsoft Corporation",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=7.00,
            tick_size=0.01,
            last_price=300.00,
            open_price=295.00,
            high_price=302.00,
            low_price=294.00,
            close_price=298.00,
            bid_price=299.00,
            bid_size=80,
            ask_price=301.00,
            ask_size=80,
            volume=800000,
        )
        Stock.objects.get_or_create(
            symbol="TSLA",
            name="Tesla, Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=15.00,
            tick_size=0.01,
            last_price=700.00,
            open_price=690.00,
            high_price=705.00,
            low_price=685.00,
            close_price=695.00,
            bid_price=698.00,
            bid_size=60,
            ask_price=702.00,
            ask_size=60,
            volume=600000,
        )
        Stock.objects.get_or_create(
            symbol="AMZN",
            name="Amazon.com, Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=12.00,
            tick_size=0.01,
            last_price=3500.00,
            open_price=3480.00,
            high_price=3520.00,
            low_price=3470.00,
            close_price=3490.00,
            bid_price=3495.00,
            bid_size=40,
            ask_price=3505.00,
            ask_size=40,
            volume=400000,
        )
        Stock.objects.get_or_create(
            symbol="FB",
            name="Meta Platforms, Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=8.00,
            tick_size=0.01,
            last_price=350.00,
            open_price=345.00,
            high_price=352.00,
            low_price=344.00,
            close_price=348.00,
            bid_price=349.00,
            bid_size=70,
            ask_price=351.00,
            ask_size=70,
            volume=700000,
        )
        Stock.objects.get_or_create(
            symbol="NFLX",
            name="Netflix, Inc.",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=9.00,
            tick_size=0.01,
            last_price=550.00,
            open_price=540.00,
            high_price=555.00,
            low_price=535.00,
            close_price=545.00,
            bid_price=548.00,
            bid_size=30,
            ask_price=552.00,
            ask_size=30,
            volume=300000,
        )
        Stock.objects.get_or_create(
            symbol="BRK.B",
            name="Berkshire Hathaway Inc.",
            exchange="NYSE",
            currency="CAD",
            limit_price_band=20.00,
            tick_size=0.01,
            last_price=280.00,
            open_price=275.00,
            high_price=282.00,
            low_price=274.00,
            close_price=278.00,
            bid_price=279.00,
            bid_size=55,
            ask_price=281.00,
            ask_size=55,
            volume=550000,
        )
        Stock.objects.get_or_create(
            symbol="NVDA",
            name="NVIDIA Corporation",
            exchange="NASDAQ",
            currency="CAD",
            limit_price_band=11.00,
            tick_size=0.01,
            last_price=220.00,
            open_price=215.00,
            high_price=222.00,
            low_price=214.00,
            close_price=218.00,
            bid_price=219.00,
            bid_size=90,
            ask_price=221.00,
            ask_size=90,
            volume=900000,
        )
        Stock.objects.get_or_create(
            symbol="JPM",
            name="JPMorgan Chase & Co.",
            exchange="NYSE",
            currency="CAD",
            limit_price_band=6.00,
            tick_size=0.01,
            last_price=160.00,
            open_price=158.00,
            high_price=161.00,
            low_price=157.00,
            close_price=159.00,
            bid_price=159.50,
            bid_size=65,
            ask_price=160.50,
            ask_size=65,
            volume=650000,
        )
        Stock.objects.get_or_create(
            symbol="XEQT",
            name="iShares Core Equity ETF Portfolio",
            exchange="TSX",
            currency="CAD",
            limit_price_band=2.00,
            tick_size=0.01,
            last_price=50.00,
            open_price=49.50,
            high_price=50.50,
            low_price=49.00,
            close_price=49.80,
            bid_price=49.90,
            bid_size=200,
            ask_price=50.10,
            ask_size=200,
            volume=2000000,
        )
        Stock.objects.get_or_create(
            symbol="VEQT",
            name="Vanguard FTSE Global All Cap ex Canada Equity Index ETF",
            exchange="TSX",
            currency="CAD",
            limit_price_band=2.50,
            tick_size=0.01,
            last_price=60.00,
            open_price=59.50,
            high_price=60.50,
            low_price=59.00,
            close_price=59.80,
            bid_price=59.90,
            bid_size=180,
            ask_price=60.10,
            ask_size=180,
            volume=1800000,
        )
        Stock.objects.get_or_create(
            symbol="BTC",
            name="Bitcoin CAD",
            exchange="Crypto",
            currency="CAD",
            limit_price_band=5000.00,
            tick_size=0.01,
            last_price=45000.00,
            open_price=44000.00,
            high_price=45500.00,
            low_price=43500.00,
            close_price=44500.00,
            bid_price=44400.00,
            bid_size=10,
            ask_price=44600.00,
            ask_size=10,
            volume=1000,
        )

        self.stdout.write(self.style.SUCCESS("Stock data seeded successfully."))
